### PR TITLE
Provide content in eu and es languages

### PR DESCRIPTION
**Pull request by erral**
Hi:

We plan to create a demo site in Spanish (es) and Basque (eu) and I translated the po file for both languages and prepared the zexp files with the contents.

It is not useful perhaps for demo.plone.de but perhaps someone that uses this to demo plone in another site can find it useful.

### CODE REVIEW

**Comment by pbauer** [comment]
@erral Sorry, I missed this pull-request. That is excellent! I agree most people will not be able to read basque 😉 Anyway I love it and would like to deploy it if you agree. We could easlily point additional domains at this site and have less work in maintaining it.  

In 6bbb0a338e79c4df683139d3d2816deb282c8670 I enabled the new languages.

**Comment by erral** [comment]
Nice!

For the moment the plans to provide a demo site are just plans, nothing defined yet. When we have something  clearer I'll ping you.

**Comment by pbauer** [comment]
@erral Whopee! I deployed it: http://demo.plone.de/eu 

If you have a domain you can point it at 141.84.94.172 and add it to the nginx-config (https://github.com/collective/demo.plone.de/blob/master/templates/nginx.conf)

**Comment by erral** [comment]
Nice, thanks!!

**Pull request merged**
